### ISSUE TITLE
Does LCMCore still need Python?

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/LCMCore.jl#60]
Curious, is Python still needed for LCMCore? I know it was a while back but thought it was removed. 

It seems to still be in the deps though: https://github.com/JuliaRobotics/LCMCore.jl/blob/master/deps/build.jl#L24

**Comment by tkoolen** [comment]
I don't think so, no. That was kind of the point of lcmcore. @rdeits?

**Comment by rdeits** [comment]
No, we shouldn't need python at all. I believe it's still in the build process because it is necessary if you want to use [PyLCM](https://github.com/rdeits/PyLCM.jl), but given all of the great work on native Julia LCM types that Twan has done, I think we should get rid of python from the build and move any of that logic over to PyLCM (or, frankly, just deprecate PyLCM since I haven't used it in years).
